### ISSUE TITLE
Official repository management

### ISSUE THREAD

**Issue by Informatic** [webosbrew/webos-homebrew-channel#10]
We need to build some infrastructure and rules for managing official webosbrew package repository.

**Comment by mariotaku** [comment]
Currently there are 2 known homebrew apps right, hbchannel and Moonlight? I consider they're "officially" supported. So I think I could 
1. Generate package manifest of ipk and upload along with releases
2. Generate repository info with some scripts
3. Deploy this into a static repo e.g. `webosbrew.github.io`

**Comment by Informatic** [comment]
I've been mostly thinking about figuring out the rules for user-submitted homebrew.

There are at least a bunch of other apps that I can think of:
1. [Chocolate Doom](https://github.com/webosbrew/chocolate-doom) (even if that's going to be a tiny demo to get people excited about webos homebrew)
2. https://github.com/FriedChickenButt/youtube-webos - this is the part I mostly meant regarding setting the rules - shall we accept apps like this? I guess we don't want to get involved in (too many) legal battles. Some obvious piracy-related apps are no-go - but where do we draw the line?

**Comment by mariotaku** [comment]
1. In this case I should at least build a version which could be opened by launcher, and load a data file that is allowed to be redistributed.
2. For user submitted homebrew, we can simply ask apps with legal concern to host the repo info on their own - but implement some "Add to hbchannel button" feature to let user install easily.

Later if we want to accept user submission, we could let them submit some kind of pull request. Feeling a bit sleepy so I may not be able to describe clearly. But I'll make a quick demo and show here tomorrow :)

**Comment by mariotaku** [comment]
Looks like I'm running late! Will do this tonight (GMT+9).

**Comment by mariotaku** [comment]
Repo is now at: https://github.com/webosbrew/apps-repo
Next my plan is to
1. Use Github Actions to generate repo json
2. Publish to gh-pages
3. Give this repo a CNAME e.g. `repo.webosbrew.org`
4. (Nice to have) provide a static page to show listed apps on browsers.

**Comment by mariotaku** [comment]
I think this can be closed :)

**Comment by Informatic** [comment]
Sure, this is mostly done, any further issues will be handled in `webosbrew/apps-repo`.
