### ISSUE TITLE
did something happen recently - instant crashes

### ISSUE THREAD

**Issue by bugsbunny88** [webosbrew/webos-homebrew-channel#109]
Hi there,
We were watching the youtube ad free thing for the very first time ...
we have been using jellyfin for a while now ; but youtube first time.
the TV is in a state where it just immedately crashes after a few seconds.

any guidance or HowTo ?

I suppose a very basic question would be how to identify the source of the crash in the first place
I get popops for 'tv was turned off and update has stopped.. do you want to restart the update now.." 
and "failsafe mode remove file /var/luna/preferences/homebrew_failsafe"

I am on v0.5
webOS TV 6.2.1 LGwebOSTV

**Comment by mariotaku** [comment]
If you turn off failsafe mode, and restart your TV, will it crash again?

**Comment by mksy** [comment]
> Hi there, We were watching the youtube ad free thing for the very first time ... we have been using jellyfin for a while now ; but youtube first time. the TV is in a state where it just immedately crashes after a few seconds.

can you test it for official youtube?

**Comment by Informatic** [comment]
No response. For anyone looking for similar issue: check what/if you have any scripts in `/var/lib/webosbrew/init.d` - buggy startup scripts can stall main startup sequence, and cause failsafe mode flag to not get removed on boot finish.
