### ISSUE TITLE
Add EShare application to store

### ISSUE THREAD

**Issue by lexcorp** [webosbrew/webos-homebrew-channel#111]
EShare is a multi-screen interaction application which makes the user experience natural and enjoyable for home entertainment, business presentation, and educational training. To use this app on your Android phone or tablet, you need a TV/Projector/IFPD/IWB with EShareServer or ESharePro pre-installed.

Mirror from TV screen to PC

https://play.google.com/store/apps/details?id=com.eshare.clientv2&hl=es&gl=US

https://www.youtube.com/watch?v=r2SitEmphb0

**Comment by Informatic** [comment]
This is unactionable by us - ask a vendor of that application to port it to webOS.
