### ISSUE TITLE
Extend netcast operating system support

### ISSUE THREAD

**Issue by wuniversales** [webosbrew/webos-homebrew-channel#115]
I don't know if it would be possible, in my case I have a Smart TV LG Netcast OS.
I have forkplayer installed, loaded by USB, this makes me think that maybe you can also run applications like this....
Would it be possible to load applications like this on the smart tv?
Could the homebrew channel support be extended to support Netcast as well?

Thanks. Regards

**Comment by Informatic** [comment]
NetCast is a completely different platform, and thus Homebrew Channel will not work there, unless someone basically reimplemented it from scratch. I doubt that will ever happen, since NetCast is so old. Sorry.
