### ISSUE TITLE
[app idea] a video player better than LG's

### ISSUE THREAD

**Issue by 5wHN28Dg** [webosbrew/webos-homebrew-channel#119]
The built-in video player is very limited in its features

The main things that want it to be better are:
- better support for subtitles
- better support for video and audio codecs

**Comment by Informatic** [comment]
Unrelated to homebrew channel - https://github.com/webosbrew/apps-repo has some issues with app ideas, but this is pretty much unactionable at this point. If **you** want to implement such an app - go for it. Otherwise - nothing to do here.
