### ISSUE TITLE
ssh connection not possible [webos 4.9.5-10]

### ISSUE THREAD

**Issue by oliv615** [webosbrew/webos-homebrew-channel#120]
Hi ! I have a problem connecting to ssh (also telnet or Device Manager). 
The root status is "ok" and I have enabled SSH.
The error message with putty or powershell is "connect to host 192.168.1.94 port 22: Connection refused" (before even asking me for credentials).
webos version 4.9.5-10
Thank you for your help and for this great application.

**Comment by mksy** [comment]
it seems your firmware was updated, and startup.sh was restored to original one.
what version of homebrew channel do you have? you need to update it to 0.5.1

**Comment by oliv615** [comment]
Thank you for your help. 
There was no update. I followed the root procedure and I could never connect in ssh even if the root was successful. I am using version 0.51

**Comment by oliv615** [comment]
Maybe the next homebrew channel update will solve my problem. Is a new version already planned? Thanks.

**Comment by Doridian** [comment]
Hitting the same issue as well on my webOS TV. (webOS 4.4.2-10).
Somehow the `startup.sh` just does not get executed at all. (Using latest 0.5.1 version)

**Comment by Informatic** [comment]
Startup on webOS 4.5+ is supported since Homebrew Channel v0.5.1.
Startup on older "patched" webOS versions is already reported in #124, still unsolved.
