### ISSUE TITLE
Unable to connect to the network

### ISSUE THREAD

**Issue by ManyMilesAway** [webosbrew/webos-homebrew-channel#122]
Homebrewed my 55UJ6200-UA running webOs 3.9.1
It worked well for a few hours but after turning it off and coming back later, Wi-Fi connection doesn't work.

It tries to connect to my home Wi-Fi and says
"Unable to connect to the network.
Wi-Fi issue has occurred.
Please check the status and try again."

**Comment by Plasmapea987** [comment]
I fixed this issue by factory resetting my tv. but i cant jailbreak it afterwards :/

**Comment by Informatic** [comment]
That sounds odd, and I can't imagine how this may be related to Homebrew, sadly.
