### ISSUE TITLE
Install/launch options greyed out.

### ISSUE THREAD

**Issue by aresbrutus** [webosbrew/webos-homebrew-channel#123]
Hello everyone. 

After I start up the homebrew up and click any of the apps, the buttons to install or launch are greyed out. This means that I can not install anymore new apps. Is there a reason why this might happen? Thanks in advance!

**Comment by Informatic** [comment]
Hey! We noticed an fd leaking bug on certain startup setups (non-rootmytv) that caused our service to break after 60 seconds of TV startup - reboot your TV (if you have quickstart+ enabled you may need to unplug it from power completely for it to do a full reboot) and try updating to latest Homebrew Channel version immediately - this should alleviate the issue on further reboots.

**Comment by throwaway96** [comment]
Should be fixed in 0.6.0 (commits 66ce8e9 and/or 79ca954).
