### ISSUE TITLE
Error after Factory reset 

### ISSUE THREAD

**Issue by Im2fat2fly** [webosbrew/webos-homebrew-channel#126]
Hello, I've had rooted my tv well over a year now. I factory reset my tv, cause of a problem and when i went to re-root it again, it comes with an error. I've attached a picture, so you can see what error it comes up with. 
![IMG_20221114_191341](https://user-images.githubusercontent.com/118212151/201737016-8a728728-9226-40f4-8c5a-f587c2c80fb9.jpg)

**Comment by DavidBuchanan314** [comment]
Your TV appears to have been updated to a patched firmware version

**Comment by Im2fat2fly** [comment]
Means it wont work on my tv anymore?

**Comment by Im2fat2fly** [comment]
Would like to fix this issue, cause i cant live without adfree youtube, aha
