### ISSUE TITLE
Paramount+ app on WebOS 3.x

### ISSUE THREAD

**Issue by domerich** [webosbrew/webos-homebrew-channel#129]
Hi guys

is there a way to bring Paramount+ to pre 2018 LG TVs running webOS 3.x? 

Would be great!

**Comment by Soliver84** [comment]
same here with the aktual Software
![IMG_20221207_160627](https://user-images.githubusercontent.com/11579411/206509651-85cc27bb-cd41-4498-85d8-2e9494584c79.jpg)

**Comment by domerich** [comment]
> same here with the aktual Software ![IMG_20221207_160627](https://user-images.githubusercontent.com/11579411/206509651-85cc27bb-cd41-4498-85d8-2e9494584c79.jpg)

how do you mean?

**Comment by Soliver84** [comment]
I can't load the "Paramount Plus" app with this firmware either

**Comment by Soliver84** [comment]
It would be great if someone who has a 4x TV can upload it

**Comment by Soliver84** [comment]
Can one of the devs do that, please

**Comment by Soliver84** [comment]
yes that would be great. because the system is still maintained by LG.

**Comment by domerich** [comment]
There is some different information

Supported models and versions
LG TV is supported on:

    All LG TVs with webOS 4.0 or higher (2018 - current models)

https://help.paramountplus.com/s/article/PD-How-can-I-stream-Paramount-on-my-LG-TV

**Comment by Soliver84** [comment]
why doesn't this have to do with: Homebrew Channel to do, everyone wants the app. and yes, as of 4.0, the app does exist. it would be cool if the dan comes in the shop. every OS 3x user says thank you.
