### ISSUE TITLE
webOS TV-Version 7.2.0-44 - Dropbear ssh not working 

### ISSUE THREAD

**Issue by 0xBADEAFFE** [webosbrew/webos-homebrew-channel#130]
I rooted my new lg c2 tv and noticed that ssh is not working.

webOS version:
`~ # uname -a
Linux LGwebOSTV 5.4.96-266.mlt4tv.1 #1 SMP PREEMPT Tue Nov 8 12:52:11 UTC 2022 aarch64 GNU/Linux
`

Content of lib folder:
`/lib # ls 
depmod.d                   libfdisk.so.1              libresolv.so.2
ecryptfs                   libfdisk.so.1.1.0          librt-2.31.so
firmware                   libgcc_s.so.1              librt.so.1
ld-2.31.so                 libm-2.31.so               libsmartcols.so.1
ld-linux.so.3              libm.so.6                  libsmartcols.so.1.1.0
libBrokenLocale-2.31.so    libmount.so.1              libss.so.2
libBrokenLocale.so.1       libmount.so.1.1.0          libss.so.2.0
libSegFault.so             libncurses.so.5            libsystemd.so.0
libSegFault.so.1           libncurses.so.5.9          libsystemd.so.0.27.1
libanl-2.31.so             libncursesw.so.5           libtinfo.so.5
libanl.so.1                libncursesw.so.5.9         libtinfo.so.5.9
libblkid.so.1              libnsl-2.31.so             libudev.so.1
libblkid.so.1.1.0          libnsl.so.1                libudev.so.1.6.16
libc-2.31.so               libnss_compat-2.31.so      libusb-0.1.so.4
libc.so.6                  libnss_compat.so.2         libusb-0.1.so.4.4.4
libcap-ng.so.0             libnss_dns-2.31.so         libusb-1.0.so.0
libcap-ng.so.0.0.0         libnss_dns.so.2            libusb-1.0.so.0.1.0
libcap.so.2                libnss_files-2.31.so       libutil-2.31.so
libcap.so.2.32             libnss_files.so.2          libutil.so.1
libcom_err.so.2            libnss_mdns.so.2           libuuid.so.1
libcom_err.so.2.1          libnss_mdns4.so.2          libuuid.so.1.3.0
libdl-2.31.so              libnss_mdns4_minimal.so.2  libwrap.so.0
libdl.so.2                 libnss_mdns6.so.2          libwrap.so.0.7.6
libe2p.so.2                libnss_mdns6_minimal.so.2  libz.so.1
libe2p.so.2.3              libnss_mdns_minimal.so.2   libz.so.1.2.11
libecryptfs.so.1           libnss_myhostname.so.2     modprobe.d
libecryptfs.so.1.0.0       libpthread-2.31.so         modules
libext2fs.so.2             libpthread.so.0            systemd
libext2fs.so.2.4           libresolv-2.31.so          udev`

Dropbear can't be executed, this is the error:
`/media/developer/apps/usr/palm/services/org.webosbrew.hbchannel.service/bin # ./dropbear
./dropbear: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory`

Could you provide a new release which is compatible with newer webOSTV versions?

**Comment by Informatic** [comment]
Homebrew Channel v0.6.1 should already work on webOS 7+
