### ISSUE TITLE
"Block Update" works mostly

### ISSUE THREAD

**Issue by SyCoREAPER** [webosbrew/webos-homebrew-channel#131]
While "Block Updates" works at blocking the software, the TV is still phoning home to the update servers. 

Every time I turn the TV on it prompts me (Yes/No) to update the latest firmware.

Any way to block this?

**Comment by nurikk** [comment]
Try this 

```
echo "mount --bind /bin/false /usr/sbin/update
pkill -9 -f /usr/sbin/update" > /var/lib/webosbrew/init.d/noupdate && chmod +x /var/lib/webosbrew/init.d/noupdate && /var/lib/webosbrew/init.d/noupdate
```

**Comment by pannal** [comment]
This plus blocking `su.lge.com`, `snu.lge.com` and `su-ssl.lge.com` removed my update notification (and somewhat borked the "version information" section of my "About this TV" menu.

Version information can now only be retrieved using 1111 on the Programmes menu.

**Comment by SyCoREAPER** [comment]
@nurikk @pannal

Thank you for your suggestions. Unfortunately while I was in HB and playing with the block update, inbetween changes I forgot to reboot and my wife accidentally updated.

I am still rooted (I think) but from what I read I'm screwed if I ever factory reset at this point.

**Comment by athossampayo** [comment]
> Try this 
> 
> 
> 
> ```
> 
> echo "mount --bind /bin/false /usr/sbin/update
> 
> pkill -9 -f /usr/sbin/update" > /var/lib/webosbrew/init.d/noupdate && chmod +x /var/lib/webosbrew/init.d/noupdate && /var/lib/webosbrew/init.d/noupdate
> 
> ```

I can confirm this solution is needed to make sure the prompt doesn't appear on boot. 

Shouldn't we add it to the startup.sh on the repo?

**Comment by SyCoREAPER** [comment]
Closing as this no longer applies to me
