### ISSUE TITLE
What to do after WebOs update?

### ISSUE THREAD

**Issue by tarnegur** [webosbrew/webos-homebrew-channel#132]
I didn't knew about the patch in the LG firmware and my TV got updated. Now all the apps are gone. What can I do now? I played with the developer mode, installed the Homebrew app, it worked, but after 46hrs or so is everything gone again....

**Comment by bkbartk** [comment]
Lg dev mode session only lasts 50 hours. 
min the windows application I used for installing home brew there are instructions on how to renew those automatically. 
you can tweak them a bit if you like.

**Comment by tarnegur** [comment]
is this the only option by now?

**Comment by gibahjoe** [comment]
I updated my TV too and all the apps were gone. I just needed to rerun the rooting process

**Comment by tarnegur** [comment]
If it were so easy.... I tried it also with no effect. My WebOs version is 06.10.30, I run the rooting over the roomy.tv page in browser. The TV reboots, but there is no homebrew app installed then.

**Comment by gibahjoe** [comment]
Try the crashd method. It worked for me when rootmytv didn't. 

https://gist.github.com/throwaway96/e811b0f7cc2a705a5a476a8dfa45e09f

**Comment by tarnegur** [comment]
I can only make it to the Putty point. The touch command gives no error, but Putty sais "connection refused"))

**Comment by gibahjoe** [comment]
Did you check the port was correct? its meant to be 23 (i think)

**Comment by tarnegur** [comment]
Yes I did.
