### ISSUE TITLE
Lost Homebrew and Developer Mode access

### ISSUE THREAD

**Issue by Coumodo** [webosbrew/webos-homebrew-channel#136]
Today my LG OLED65B7D with webOS 06.10.30 had an error report message after starting.
After reboot the TV Homebrew was gone...
Tried rootmy.tv again, passes with out problems but doesn't install Homebrew (no Homebrew after reboot).
Now I want to try out other ways to root webOS, but Developer Mode also doesn't work any more!?
Same as rootmy.tv - can select Dev mod. "ON" in app, reboot -> Dev. mod. still not aktive. (tried multiple times)
Don't know how to proceed?!
Need Jellyfin out of Homebrew deposite.

**Comment by throwaway96** [comment]
You may need to factory reset your TV in order to get Developer Mode working again. It doesn't like `devmode_enabled` being a directory.
