### ISSUE TITLE
What ports are open for telnet connections?

### ISSUE THREAD

**Issue by DarkXSeries7** [webosbrew/webos-homebrew-channel#137]
title

**Comment by throwaway96** [comment]
23

**Comment by DarkXSeries7** [comment]
nope
![image](https://user-images.githubusercontent.com/68074009/228292373-a93e9c1a-a6b5-4edf-b019-ac03111d43b7.png)
webos doesent want to connect even when using ip control (tv is not rooted i am trying to send commands over ip)

**Comment by throwaway96** [comment]
Port 23 isn't going to be open unless either:
* you start `telnetd` manually (e.g., during the process of rooting), or
* it's started automatically by Homebrew Channel on boot.

I'm not sure what you're trying to do, but it doesn't seem related to Homebrew Channel. I came across one TV where I was able to use TV-Link commands on port 9761 (TCP), but it was a commercial model.
