### ISSUE TITLE
en error occurred during installation org.webosbrew hp channel.service is not running

### ISSUE THREAD

**Issue by sereose** [webosbrew/webos-homebrew-channel#140]
Hello I'm getting this error during app installation process.
"en error occurred during installation org.webosbrew hp channel.service is not running"
LG  UH7507
WebOS  05.60.25
root - enabled.
org.webosbrew v.0.4.0

**Comment by Informatic** [comment]
Can you connect to the TV as root using telnet or ssh? Have you tried rebooting the TV? (there's an option for that in Homebrew Channel Settings view)

**Comment by sereose** [comment]
Thank  you for the quick response  
Problem solved.
Just need to read the manual guide more carefully 
(root) Elevate privileges by running:
/media/developer/apps/usr/palm/services/org.webosbrew.hbchannel.service/elevate-service
(root) Update startup script:
cp /media/developer/apps/usr/palm/services/org.webosbrew.hbchannel.service/startup.sh /var/lib/webosbrew/startup.sh
