### ISSUE TITLE
LG C2 - Lost root access after Update to homebrew channel v0.6.2

### ISSUE THREAD

**Issue by 0xBADEAFFE** [webosbrew/webos-homebrew-channel#141]
After updating to to homebrew channel v0.6.2 on my LG C2, I no longer have root access. Even deactivating QuickStart+ did not help.

**Comment by Informatic** [comment]
How did you update your Homebrew Channel? What was the previous Homebrew Channel version you had installed?

**Comment by 0xBADEAFFE** [comment]
I had installed version v0.5.1 and updated to the new version in the app.

**Comment by Informatic** [comment]
Just to clarify - in Homebrew Channel app itself? That sounds odd. Doing some investigation. Did you notice any notifications when performing an update? Normally self-updates should emit the following notifications:
* Performing self-update...
* Performing self-update (inner)
* Elevating...
* Self-update finished!

Figuring out which step failed may help with investigation.

**Comment by 0xBADEAFFE** [comment]
Yes I did the update in the Homebrew Channel app. I did not get the notifications and after reboot root access and ssh/telnet is missing. The app YouTube Adfree, which I installed via Hombrew, still works.

**Comment by Informatic** [comment]
Update: we've discovered `tar` has been replaced with `busybox` applet in webOS 22, breaking [our oneliner responsible for package info extraction](https://github.com/webosbrew/webos-homebrew-channel/blob/main/services/service.ts#L151), which we use to detect homebrew channel self-updates.

We're investigating potential recovery and safe self-update method for webOS 22.

**Comment by throwaway96** [comment]
Fixed in 0.6.3 (0d4d893).
