### ISSUE TITLE
An error has occured while downloading some repositories from homebrew

### ISSUE THREAD

**Issue by ice051128** [webosbrew/webos-homebrew-channel#154]
For whatever reasons, homebrew channel refuses to load anything right now even tho it has worked in the past. The page is simply blank when u enter the app and when u hit the refresh button it says "An error has occured while downloading some repositories from https://repo.webosbrew.org/api/apps.json" something like that. My homebrew version is 0.5.0.

How do u fix this?

**Comment by op3djl** [comment]
Same issue for me. I manually upgraded to homebrew 0.6.3, which made no difference.

**Comment by op3djl** [comment]
The same error when I only enable the non-free repositories: "An error occured while downloading some repositories: https://repo.webosbrew.org/api/non-free/apps.json(0)"

**Comment by NipponBill** [comment]
Same error here.

> An error occurred while downloading some repositories: https://repo.webosbrew.org/api/apps.json (0)

- webosbrew version: **0.6.3**
- Root status: **ok**
- Extra non-free software - _not enabled_

**Comment by NipponBill** [comment]
The error miraculously went away and the home page is once again populated with apps.

**Comment by op3djl** [comment]
Yes, ditto for me.

**Comment by NipponBill** [comment]
Something likely changed in https://repo.webosbrew.org/api/apps.json
Didn't think to do this before, but I archived the current file so I'll have something to compare if this happens again https://archive.is/sla0K

**Comment by Artem1-cmyk** [comment]
An error occurred while downloading some repositories: https://repo.webosapp.club (600) How to solve the problem

**Comment by Lilicogamer13** [comment]
i know this is gonna sound repetitive, but have you tried doing a system reboot?

**Comment by bastiHST90** [comment]
The normal apps work fine for me. But an added repository doesn't load. It worked a couple months ago, so it isn't a typo. And it seems the link itself should work fine.
No idea what I could do, homebrew app is latest version and I rebooted.
My DNS is Google. It always was for the last years.

TV is a OLED C9, Software version 05.20.07

**Comment by retropele** [comment]
Just for reference if someone has this same issue, sometimes the problem is the system time (especially if you don't allow the TV to auto-update time/your DNS filter blocks the time/date servers). If the system time is wrong (and my TV will lose this data on crash) and it can't auto update, you won't be able to access any repository really until it's adjusted.
