### ISSUE TITLE
Certificate error during download/installation: "certificate has expired"

### ISSUE THREAD

**Issue by brianeng00** [webosbrew/webos-homebrew-channel#167]
I’m getting an error when trying to install from the Homebrew Channel. It says “An error occurred during installation: request to https://mirrors.kodi.tv/releases/webos/org.xbmc.kodi-webos_21.0~b1.ipk failed, reason: certificate has expired

**Comment by throwaway96** [comment]
@romerotsvk

That comment was not about you. But if you really want to know anyway, the space was between `webos` and `/org` in the first line of [this comment](https://github.com/webosbrew/webos-homebrew-channel/issues/167#issuecomment-1924491992).
