### ISSUE TITLE
Certificate error while Homebrew app installation (issue came back)

### ISSUE THREAD

**Issue by AntonFaer** [webosbrew/webos-homebrew-channel#181]
![PXL_20240403_211939904.MP.jpg](https://github.com/webosbrew/webos-homebrew-channel/assets/163782276/450270d3-2e57-4439-8a24-3e15695364f8)

Does anyone know how to fix this?
TIA

LG OLED65C7P
SV: 06.05.10

**Comment by kitsuned** [comment]
dup of #179.
