### ISSUE TITLE
New root vulnerability announced by LG 

### ISSUE THREAD

**Issue by orangpelupa** [webosbrew/webos-homebrew-channel#182]
https://arstechnica.com/security/2024/04/patches-released-for-as-many-as-91000-hackable-lg-tvs-exposed-to-the-internet/

Wondering if this allows those that didn't update to the new fw, ability to root their TV.

Although it may requires a self hosted solution

**Comment by DavidBuchanan314** [comment]
See https://github.com/RootMyTV/RootMyTV.github.io/issues/142

(short answer, yes, it looks viable)
