### ISSUE TITLE
"CERT_UNTRUSTED" error installing the hyperion project tweaks

### ISSUE THREAD

**Issue by Dreel0akl** [webosbrew/webos-homebrew-channel#185]
I am trying to install PicCap and hyperion.ng for a LED strip and i get the error "CERT_UNTRUSTED" when trying to install them both, does anyone know how to prevent this?

**Comment by VoodooZ** [comment]
Getting same problem here. Tried updating homebrew but says it's up date. 
More importantly seems google has found a way to break adfree youtube and I can't update to latest of that to find out if it has a solution.

**Comment by kitsuned** [comment]
dup of #179.
