### ISSUE TITLE
Please add cmus - C* Music Player - into webosbrew

### ISSUE THREAD

**Issue by DragonSerW** [webosbrew/webos-homebrew-channel#186]
Hello pals!
Could you please add the `cmus` package (https://cmus.github.io/) into WebOS Brew? :-)
By the way the problem I have is:
My LGs-2016 are not playing any radio stream, while they play IPTV-streams okay.

**Comment by throwaway96** [comment]
This is not relevant to Homebrew Channel. It would be more appropriate in [apps-repo](https://github.com/webosbrew/apps-repo/issues). However, this application appears to have an ncurses-based UI, and I'm not aware of any terminal emulators for webOS.

You can try compiling it yourself with [buildroot-nc4](https://github.com/openlgtv/buildroot-nc4). You'd have to use it via SSH/Telnet. Output via PulseAudio may work.
