### ISSUE TITLE
OLED55C31LA goes to sleep after 4 hours

### ISSUE THREAD

**Issue by palibrzuch** [webosbrew/webos-homebrew-channel#188]
Firmware 03.30.74
webOS 8.3.0
Homebrew 0.6.3 with root
After turning it off with the remote control every day, the TV stops being active only after 4 hours. You can connect to it via WiFi. I will add that all settings are turned off so that the TV turns off, but it only happens after 4 hours.

**Comment by kitsuned** [comment]
> The Pixel Refresher feature, built into LG OLED TVs, automatically detects
pixel deterioration through periodic scanning, compensating for it as needed.
It also senses any TFT (Thin Film Transistor) voltage changes during power off
to detect and correct pixel degradation by comparing it with a set reference value.
> 
> — https://www.lg.com/eg_en/tvs/oled-tvs/oled-reliability

either way, it has nothing to do with HBC.
such questions should be directed to LG Support.
