### ISSUE TITLE
Change wallpaper

### ISSUE THREAD

**Issue by Jostico96** [webosbrew/webos-homebrew-channel#190]
I would like to change the background image.
My LG is already rooted.

Any suggestions or way to do it?

**Comment by throwaway96** [comment]
Find the current images and bind mount over them. They might be in `/usr/palm/applications/com.webos.app.igallery/assets/artgallery1`, but it varies by model. But this is not related to Homebrew Channel.

**Comment by Jostico96** [comment]
Yes is not related to  homebrew Channel.
But I had some idea who could help me change the wallpaper.
Thank you good person.
