### ISSUE TITLE
crunchyroll app not working

### ISSUE THREAD

**Issue by lebang1** [webosbrew/webos-homebrew-channel#195]
It say invalid login. But the username and password is ok.

Under invalid login is also something like:
file://media/developer/apps/usr/palm/applications/com.crunchyroll.webos/scripts/main.js:2034:27 
at step. And 3 other similar.

**Comment by dougNetD** [comment]
already open issue:  https://github.com/mateussouzaweb/crunchyroll-webos/issues

**Comment by mariotaku** [comment]
For apps in the channel, please send issues/requests to respective developers.
