### ISSUE TITLE
After updating to 0.7.1 I can't install or uninstall apps

### ISSUE THREAD

**Issue by lupalby** [webosbrew/webos-homebrew-channel#199]
I have used homebrew channel for more than a year without any problem. My TV is not rooted, I used the dev mode.

I recently realized that there was an update of the homebrew channel app and I did it from within the app itself. Everything seemed good until I realized that now I can't install or uninstall any application from inside the homebrew channel. No matter which app page I open, all update/install/uninstall buttons are not clickable, including for YouTube adfree that I have installed. I tried to restart the TV many times, including using the trick of refusing the condition agreement, and nothing changes.

**Comment by mareksipos93** [comment]
Same issue, all buttons are greyed out and non-clickable.

**Comment by hyperanalysis** [comment]
Exactly the same here - version 0.7.1 no root/dev mode - Install/Launch/Uninstall all grayed out
Used Dev Manager on laptop to reinstall Homebrew and YouTube but still grayed out in WebOS app.

**Comment by Scott-Pearce** [comment]
You have to press "5" on your remote to unlock those buttons for some reason.

**Comment by lupalby** [comment]
Pressing 5 only enabled a "reinstall" option. Uninstall stays not clickable.

**Comment by mareksipos93** [comment]
I have no numbers on my LG remote

**Comment by mariotaku** [comment]
@lupalby @mareksipos93 What's the model of the TV? Without further information we couldn't reproduce that.

**Comment by lupalby** [comment]
My TV is a OLED65A19LA.

For the others in my situation: a few days ago I noticed that the latest version of homebrew channel available is not 0.7.x anymore, but it's 0.6.3, so I used the trick of pressing 5 suggested above to do a reinstall, so now I practically rolled back to the old version and now the update/install/uninstall buttons are working again.

**Comment by mareksipos93** [comment]
Mine is 55" LG 55QNED813

**Comment by mariotaku** [comment]
Is that webOS 7/8? Since you're not having root, could you try uninstall and reinstall?

**Comment by lupalby** [comment]
I tried reinstalling in the past using my laptop but it didn't make any difference. 
webOS version is 6.4.0-21 (kisscurl-kluane)

**Comment by mariotaku** [comment]
Thanks to the information you provided, I can reproduce this now. It will be fixed in the next release.

**Comment by mariotaku** [comment]
Please update to v0.7.2 and let us know if it works!

**Comment by lupalby** [comment]
Thanks for the fix! Unfortunately the update doesn't show up in the homebrew channel, 0.6.3 still seems to be the latest.

**Comment by lupalby** [comment]
Now the update shows up. I updated to 0.7.2 and now I see install/update/start/uninstall available as usual. Thanks!
