### ISSUE TITLE
Limited access to luna://com.webos.appInstallService/dev/install

### ISSUE THREAD

**Issue by Informatic** [webosbrew/webos-homebrew-channel#23]
I just got a report of a webOS 4.3 device where access to install method from homebrew channel app gets denied.
```js
{ returnValue: false,
  errorCode: -1,
  errorText: 'Denied method call "install" for category "/dev"' }
```
This breaks our somewhat accidental support of unrooted devices, as we'll need to patch some ls2 permission files in elevation script to let use use these APIs.

**Comment by mariotaku** [comment]
There is another approach, to access ssh server locally, user isn't rooted and installed devmode.

**Comment by Informatic** [comment]
As a way of supporting unrooted devices? Yes, makes sense. We can implement it later.

**Comment by mariotaku** [comment]
This issue could be linked to #34 and #38 .
