### ISSUE TITLE
scp not working

### ISSUE THREAD

**Issue by Informatic** [webosbrew/webos-homebrew-channel#27]
Rel #5 - `scp` doesn't seem to work when connecting to our custom-built dropbear sshd. Likely some extra binary is missing. Needs investigation. (I think this was also broken on devmode sshd, so not really a new bug, but something definitely nice to have fixed)

Quick fix in case anyone stumbles upon this and needs to quickly pull/push a file:
```sh
cat local-path | ssh root@tv 'cat > remote-path'
ssh root@tv cat remote-path > local-path
```

**Comment by Zopieux** [comment]
Indeed, run scp verbose (`-vvv`), this works by invoking scp on the remove (TV) side which obviously we don't have.

I'm preparing a patch, consider this assigned to me.
