### ISSUE TITLE
Non-root mode via localhost ssh

### ISSUE THREAD

**Issue by Informatic** [webosbrew/webos-homebrew-channel#34]
We most likely can access nduid as an application - we could in theory pull ssh key off local keyserver and use that to access local sshd on non-rooted systems.

**Comment by mariotaku** [comment]
Did you adopt this task? I'd like to handle this if not.

**Comment by Informatic** [comment]
Feel free to take it up.

I think it'd be best to replicate `webos-service` "client-side" API using some generic nodejs ssh client library eg. https://www.npmjs.com/package/ssh2 (that's the one used by webos SDK incidentally, haven't looked deeply into it) or https://www.npmjs.com/package/node-ssh, and then just dynamically choose that implementation or directly talking with our existing `service`.

**Comment by Informatic** [comment]
This has been implemented in #38
