### ISSUE TITLE
sshd support

### ISSUE THREAD

**Issue by Informatic** [webosbrew/webos-homebrew-channel#5]
We are currently only supporting unauthenticated telnet-based remote access. We should prefer some safer solution by default - like SSH.

- [x] Bundle static dropbear sshd binary with the app
- [x] Figure out emergency situations (do we fall back to enabling telnetd in case homebrew channel gets removed, or do we copy over required binaries to some known location outside of `/media/developer`?)
- [x] Authentication bootstraping problem
  - [x] We have no way of overlaying `/etc/shadow` to set some default root password for a user (yet) - can we make dropbear accept unauthenticated users unless `authorized_keys` has been populated?
- [x] Ensure this works well enough with `ares-install` and other SDK tools

**Comment by DavidBuchanan314** [comment]
RE: authentication, could we just put this in our init script:

```sh
if [ ! -f /home/root/.ssh/authorized_keys ]; then 
  sed s/root:.:/root:xGVw8H4GqkKg6:/ /etc/shadow > /tmp/shadow
  chmod 400 /tmp/shadow
  mount --bind /tmp/shadow /etc/shadow
fi
```

i.e. if authorized_keys does not exist, set the root password to `alpine` via bind mount

**Comment by Informatic** [comment]
That makes sense.

If we put that shadowfile somewhere persistent (`/var/luna/preferences/webosbrew_shadow`?) we could also use it as a go-to solution for remote access for people inexperienced with ssh public key authentication. `passwd` should work as is with this setup, right?

**Comment by Informatic** [comment]
Initial dropbear integration is finished in 957d29f - UI is working, `tools/build-dropbear.sh` can be used to build a working customized dropbear sshd binary to be bundled with the application. Not sure how to distribute this - should we just commit the binary into the repo and call it a day?

Fully static builds seemed to fail to link when built with meta-lg-webos-ndk - not sure how to go about this, I don't have much practice with general subject of crosscompilation.

**Comment by mariotaku** [comment]
Fully static build may not work - IIRC the NDK I built doen't come with any archive files. Thus no way to static link with libc. But I think if crypto libraries could be statically linked, then it's good enough.
