### ISSUE TITLE
Supported webOS versions testing

### ISSUE THREAD

**Issue by Informatic** [webosbrew/webos-homebrew-channel#7]
Currently this has been only tested on webOS 3.3 and webOS 3.8.

Theoretically enyo should support webOS since 1.x, and service we build should work on nodejs 0.10, however this has not been tested yet.

**Comment by Informatic** [comment]
So far the UI has been designed and tested only on 4k TVs (ie. 1920x1080 rendering viewport) - we need to have someone also verify how this'll look on 1080p TVs (1280x720 rendering viewport, IIRC).

In theory preferred rendering viewport size could be changed in `appinfo.json`.

**Comment by tuxuser** [comment]
Tested on the following device

```
{
    "board_type": "LM18A_DVB",
    "device_name": "lm18a",
    "hardware_id": "HE_DTV_W18A_AFADABAA",
    "hardware_revision": "BOARD_DV_1ST",
    "product_id": "55UK6470PLC",
    "ram_size": "1.5 GB",
    "storage_size": "4 GB"
}
```

Device info

```
{
    "core_os_kernel_version": "4.4.84-636.glacier.26",
    "core_os_name": "Rockhopper",
    "core_os_release": "4.3.0-9703",
    "core_os_release_codename": "goldilocks-goobang",
    "encryption_key_type": "prodkey",
    "webos_api_version": "4.1.0",
    "webos_build_datetime": "20210107010305",
    "webos_build_id": "9703",
    "webos_imagename": "starfish-dvb-secured",
    "webos_manufacturing_version": "05.30.10",
    "webos_name": "webOS TV Lite",
    "webos_prerelease": "",
    "webos_release": "4.3.0",
    "webos_release_codename": "goldilocks-goobang"
}
```

- After homebrew channel installation, had to do the change from PR #24 (replace `public` with `all` in `/var/luna-service2-dev/client-permissions.d/org.webosbrew.hbchannel.service.service.json`), now apps install fine :)

**Comment by Ruthenic** [comment]
Tested using Homebrew Channel v0.2.1 on WebOS 5.2.1

OS Info: 
```
{
    "core_os_kernel_version": "4.4.84-612.21.6.jardine.2",
    "core_os_name": "Rockhopper",
    "core_os_release": "5.2.1-2521",
    "core_os_release_codename": "jhericurl-jardine",
    "encryption_key_type": "prodkey",
    "webos_build_datetime": "20210222052639",
    "webos_build_id": "2521",
    "webos_imagename": "starfish-atsc-secured",
    "webos_manufacturing_version": "03.21.75",
    "webos_name": "webOS TV Lite",
    "webos_prerelease": "",
    "webos_release": "5.2.1",
    "webos_release_codename": "jhericurl-jardine"
}
```
Device Info (with serial number and other potentially identifiable information removed): 
```
{
    "board_type": "K6LP_ATSC",
    "device_name": "k6lp",
    "hardware_id": "HE_DTV_W20P_AFADATAA",
    "hardware_revision": "BOARD_DV_1ST",
    "keyboard_type": "virtual",
    "modem_present": "N",
    "product_id": "43UN6950ZUA",
    "ram_size": "1.5 GB",
    "storage_size": "8 GB",
}
```
After some slight installation troubles (I can send more info here on Github if needed) which were fixed by running `ls-control scan-services` after installing, everything works fine (no changing `all` to `public` in `/var/luna-service2-dev/client-permissions.d/org.webosbrew.hbchannel.service.service.json`!).
