### ISSUE TITLE
New feature for settings: Renew certificates

### ISSUE THREAD

**Issue by DpunktKpunkt** [webosbrew/webos-homebrew-channel#74]
Older WebOS TVs have an expired root certificate for self signed Let'sEncrypt websites.

It would be nice if you could integrate [this](https://github.com/tf318/lg) as a new feature switch to homebrew settings. 
(A [small change is needed](https://github.com/tf318/lg/issues/2) as for now the bash script interferes with update blocking feature of homebrew).

Thx

**Comment by Informatic** [comment]
We are planning on making a dedicated app for that. I already cleaned up a script I used some time before, you can check that - it works pretty much the same way and shouldn't break existing webosbrew customizations:
https://github.com/webosbrew/apps-repo/issues/29#issuecomment-1003778789

**Comment by DpunktKpunkt** [comment]
Ok, closing my issue then :)
