### ISSUE TITLE
Failsafe mode notification pops up

### ISSUE THREAD

**Issue by tonyrulez** [webosbrew/webos-homebrew-channel#87]
After a power outage this notification popped up:

> Failsafe mode! Open telnet and remove
> /var/luna/preferences/webosbrew_failsafe
> 

I did remove that file using telnet, and after rebooting the TV the message keeps popping up, appearing and then disappearing after some seconds, and coming up again later. Looking into the preferences folder, the webosbrew_failsafe file is gone and did not reappear.

**Comment by tonyrulez** [comment]
Fix found: in settings, turning failsafe on and off (since it was already off) and then issuing a reboot did fix the popup of the toast notification.

**Comment by Informatic** [comment]
I don't think this really changed anything, since the switch in the UI just creates/removes that file - what is more likely is that your system is probably affected by a bug fixed in #80 - we'll release an updated version that'll fix these things next week, if it pops up again for you.
