### ISSUE TITLE
Web Video Caster  (LG PF50KG Prj.)

### ISSUE THREAD

**Issue by enderaltin** [webosbrew/webos-homebrew-channel#93]
hi, 
I appreciate your work. I have a webOS 3.0.8 projector(LG PF50KG ). but there is no LG Store. your rootmy.tv i did it with root. youtube etc. i have installed applications such as. tell me how to install applications such as netflix,Amazon, Web Video caster.

**Comment by throwaway96** [comment]
If your device didn't come with these apps, it may be lacking the necessary DRM keys.

Regardless, this is not related to Homebrew Channel.
