### ISSUE TITLE
Problems with apps installation

### ISSUE THREAD

**Issue by Newbaatt** [webosbrew/webos-homebrew-channel#94]
Please help! I installed webos homebrew through the rootmytv, installed the applications, everything was ok. Today, I can`t install any application, in any way: neither through the IDE, nor through the home brew, nor even ordinary applications with a LG content store. Writes FAILED_IPKG_INSTALL and that's it. Reboot doesn't help. At the same time, the root did not fly off, there is access through ssh, through winscp and through the IDE. Webos 4.9. What to do?

**Comment by Newbaatt** [comment]
You're right, there just wasn't enough space. Thanks for the tip! Unfortunately, I did not wait for an answer and tried again to reinstall rootmy.tv over the old one. It didn't help, but I then freed up some space and everything works. Do you think that re-installation rootmy.tv might break something in the system and how will it affect the future?

**Comment by Informatic** [comment]
Closing this since you've resolved your issue. We'll try to add some system info screen at some point to potentially help with these issues. (and potentially show a warning whenever the TV is running out of space)
