### ISSUE TITLE
Install apps from other regions

### ISSUE THREAD

**Issue by gorshco** [webosbrew/webos-homebrew-channel#97]
What are my options if I want to get ahold of and/or install an "LG store app" from a different region?

**Comment by joaopedrosgs** [comment]
Same question here.
Also, it would be nice if we could export an ipk file from the content store and then install it manually through dev-manager-desktop

**Comment by andyearnshaw** [comment]
I'd be interested to see if the Geforce Now app could run on my 55GX.

**Comment by throwaway96** [comment]
While it is possible to get IPKs for Content Store apps, they're unlikely to be useful. They are partially encrypted and will not run unless you have the correct key installed.

An unmodified Content Store app installed with Dev Manager will probably not work. Dev Mode and Content store apps are (usually) incompatible, and apps will generally fail to launch when installed as the wrong type.

There are often valid reasons for restricting apps to certain SoCs and webOS versions. LG is pretty cavalier about maintaining compatibility across webOS versions, and SoCs from different vendors can have significant differences in their video pipelines, for example. For apps limited by region, there may be restrictions on the backend as well (e.g., based on IP geolocation).

If you still want to obtain IPKs despite being aware of these obstacles, you can watch the Luna bus for URLs while an app is being downloaded. Run this command before performing an installation in the Content Store:
```
ls-monitor -f com.webos.service.downloadmanager
```
The URL will be somewhere in the output. Download the IPK quickly, as the URL will expire.

But this isn't related to Homebrew Channel.
