### ISSUE TITLE
Question: Chrome or Firefox?

### ISSUE THREAD

**Issue by agail** [webosbrew/webos-homebrew-channel#98]
Shooting from the hip as this might be the wrong place to ask.
Is there any work to bring Chrome or Firefox to the repo? 
  
I know the webos browser is based on Chrome, but its not very up to date and lack extension support.

**Comment by DavidBuchanan314** [comment]
Nobody is working on it, because it would take a relatively high amount of work.

It's not impossible, and it certainly would be useful, so you're welcome to try.
