### ISSUE TITLE
what happen? channels is down

### ISSUE THREAD

**Issue by mshakurov** [webosbrew/webos-homebrew-channel#99]
some minutes spacious post on tv - "Loading..." .
then error message at down:
An error occurred while downloading some repositories: https://repo. webosbrew. org/api/app. json(0)

All settings is default and never was changed.

**Comment by Informatic** [comment]
Everything seems to work fine.

**Comment by fdfytr** [comment]
same here for me now empty main page...
anyone can have idea on how to troubleshoot?
